// Generated by `libxr gen` from DevC.ioc and libxr_config.yaml.
// Edit only between "User Code Begin" and "User Code End"; the rest is regenerated.
#include "app_main.h"

#include "cdc_uart.hpp"
#include "flash_map.hpp"
#include "libxr.hpp"
#include "main.h"
#include "stm32_adc.hpp"
#include "stm32_can.hpp"
#include "stm32_flash.hpp"
#include "stm32_gpio.hpp"
#include "stm32_i2c.hpp"
#include "stm32_power.hpp"
#include "stm32_pwm.hpp"
#include "stm32_spi.hpp"
#include "stm32_timebase.hpp"
#include "stm32_uart.hpp"
#include "stm32_usb_dev.hpp"
#include "xrobot_main.hpp"

using namespace LibXR;

/* User Code Begin 1 */
/* User Code End 1 */

extern ADC_HandleTypeDef hadc3;
extern CAN_HandleTypeDef hcan1;
extern CAN_HandleTypeDef hcan2;
extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c3;
extern PCD_HandleTypeDef hpcd_USB_OTG_FS;
extern PCD_HandleTypeDef hpcd_USB_OTG_HS;
extern SPI_HandleTypeDef hspi1;
extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim4;
extern TIM_HandleTypeDef htim8;
extern TIM_HandleTypeDef htim10;
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart3;
extern UART_HandleTypeDef huart6;

// DMA buffers (STM32F407IG: no D-cache)
alignas(4) static uint16_t adc3_buf[64];
alignas(4) static uint8_t i2c1_buf[32];
alignas(4) static uint8_t i2c3_buf[32];
alignas(4) static uint8_t spi1_rx_buf[32];
alignas(4) static uint8_t spi1_tx_buf[32];
alignas(4) static uint8_t usart1_rx_buf[128];
alignas(4) static uint8_t usart1_tx_buf[128];
alignas(4) static uint8_t usart3_rx_buf[128];
alignas(4) static uint8_t usart6_rx_buf[512];
alignas(4) static uint8_t usart6_tx_buf[512];
alignas(4) static uint8_t usb_otg_fs_ep0_in_buf[8];
alignas(4) static uint8_t usb_otg_fs_ep0_out_buf[8];
alignas(4) static uint8_t usb_otg_fs_ep1_in_buf[128];
alignas(4) static uint8_t usb_otg_fs_ep1_out_buf[128];
alignas(4) static uint8_t usb_otg_fs_ep2_in_buf[16];
alignas(4) static uint8_t usb_otg_hs_ep0_in_buf[8];
alignas(4) static uint8_t usb_otg_hs_ep0_out_buf[8];
alignas(4) static uint8_t usb_otg_hs_ep1_in_buf[128];
alignas(4) static uint8_t usb_otg_hs_ep1_out_buf[128];
alignas(4) static uint8_t usb_otg_hs_ep2_in_buf[16];
alignas(4) static uint8_t usb_otg_hs_ep2_out_buf[128];
alignas(4) static uint8_t usb_otg_hs_ep3_in_buf[128];
alignas(4) static uint8_t usb_otg_hs_ep4_in_buf[16];

extern "C" void app_main(void)
{
  /* User Code Begin 2 */
  /* User Code End 2 */

  // Timebase and platform
  static STM32TimerTimebase timebase(&htim2);
  PlatformInit(static_cast<uint32_t>(Thread::Priority::MEDIUM), 2048);
  static STM32PowerManager power_manager;

  // GPIO
  static STM32GPIO USER_KEY(USER_KEY_GPIO_Port, USER_KEY_Pin, EXTI0_IRQn);
  static STM32GPIO ACCL_CS(ACCL_CS_GPIO_Port, ACCL_CS_Pin);
  static STM32GPIO GYRO_CS(GYRO_CS_GPIO_Port, GYRO_CS_Pin);
  static STM32GPIO HW0(HW0_GPIO_Port, HW0_Pin);
  static STM32GPIO HW1(HW1_GPIO_Port, HW1_Pin);
  static STM32GPIO HW2(HW2_GPIO_Port, HW2_Pin);
  static STM32GPIO ACCL_INT(ACCL_INT_GPIO_Port, ACCL_INT_Pin, EXTI4_IRQn);
  static STM32GPIO GYRO_INT(GYRO_INT_GPIO_Port, GYRO_INT_Pin, EXTI9_5_IRQn);
  static STM32GPIO CAMERA(CAMERA_GPIO_Port, CAMERA_Pin);
  static STM32GPIO IMU_INT(IMU_INT_GPIO_Port, IMU_INT_Pin, EXTI1_IRQn);
  static STM32GPIO CMPS_INT(CMPS_INT_GPIO_Port, CMPS_INT_Pin, EXTI3_IRQn);
  static STM32GPIO CMPS_RST(CMPS_RST_GPIO_Port, CMPS_RST_Pin);
  static STM32GPIO LED_B(LED_B_GPIO_Port, LED_B_Pin);
  static STM32GPIO LED_G(LED_G_GPIO_Port, LED_G_Pin);
  static STM32GPIO LED_R(LED_R_GPIO_Port, LED_R_Pin);

  // ADC
  static STM32ADC adc3(&hadc3, adc3_buf, {ADC_CHANNEL_8}, 3.3);
  static auto& adc3_adc_channel_8 = adc3.GetChannel(0);

  // PWM
  static STM32PWM pwm_tim1_ch1(&htim1, TIM_CHANNEL_1, false);
  static STM32PWM pwm_tim1_ch2(&htim1, TIM_CHANNEL_2, false);
  static STM32PWM pwm_tim1_ch3(&htim1, TIM_CHANNEL_3, false);
  static STM32PWM pwm_tim1_ch4(&htim1, TIM_CHANNEL_4, false);
  static STM32PWM pwm_tim10_ch1(&htim10, TIM_CHANNEL_1, false);
  static STM32PWM pwm_tim3_ch3(&htim3, TIM_CHANNEL_3, false);
  static STM32PWM pwm_tim4_ch3(&htim4, TIM_CHANNEL_3, false);
  static STM32PWM pwm_tim8_ch1(&htim8, TIM_CHANNEL_1, false);
  static STM32PWM pwm_tim8_ch2(&htim8, TIM_CHANNEL_2, false);
  static STM32PWM pwm_tim8_ch3(&htim8, TIM_CHANNEL_3, false);

  // SPI, UART, I2C, CAN
  static STM32SPI spi1(&hspi1, spi1_rx_buf, spi1_tx_buf, 3);
  static STM32UART usart1(&huart1, usart1_rx_buf, usart1_tx_buf, 5);
  static STM32UART usart3(&huart3, usart3_rx_buf, {nullptr, 0}, 5);
  static STM32UART usart6(&huart6, usart6_rx_buf, usart6_tx_buf, 15);
  static STM32I2C i2c1(&hi2c1, i2c1_buf, 3);
  static STM32I2C i2c3(&hi2c3, i2c3_buf, 3);
  static STM32CAN can1(&hcan1, 5);
  static STM32CAN can2(&hcan2, 5);

  // USB OTG FS: 1 CDC
  static constexpr auto usb_otg_fs_strings = USB::DescriptorStrings::MakeLanguagePack(
      USB::DescriptorStrings::Language::EN_US, "QDU-Future", "MainCtrl",
      "QDU-Future-MainCtrl-89ABCDEF0123456701234567");
  static USB::CDCUart usb_otg_fs_cdc(USB::Endpoint::EPNumber::EP1,
                                     USB::Endpoint::EPNumber::EP1,
                                     USB::Endpoint::EPNumber::EP2, 128, 128, 3);
  static STM32USBDeviceOtgFS usb_otg_fs(
      &hpcd_USB_OTG_FS, 256, {usb_otg_fs_ep0_out_buf, usb_otg_fs_ep1_out_buf},
      {{usb_otg_fs_ep0_in_buf, 8},
       {usb_otg_fs_ep1_in_buf, 128},
       {usb_otg_fs_ep2_in_buf, 16}},
      USB::DeviceDescriptor::PacketSize0::SIZE_8, 0x16D0, 0x1492, 0xF407,
      {&usb_otg_fs_strings}, {{&usb_otg_fs_cdc}},
      {reinterpret_cast<void*>(UID_BASE), 12});
  usb_otg_fs.Init(false);
  usb_otg_fs.Start(false);

  // USB OTG HS: 2 CDC
  static constexpr auto usb_otg_hs_strings = USB::DescriptorStrings::MakeLanguagePack(
      USB::DescriptorStrings::Language::EN_US, "QDU-Future", "MainCtrl",
      "QDU-Future-MainCtrl-89ABCDEF0123456701234567");
  static USB::CDCUart usb_otg_hs_cdc(USB::Endpoint::EPNumber::EP1,
                                     USB::Endpoint::EPNumber::EP1,
                                     USB::Endpoint::EPNumber::EP2, 128, 128, 3);
  static USB::CDCUart usb_otg_hs_cdc2(USB::Endpoint::EPNumber::EP3,
                                      USB::Endpoint::EPNumber::EP2,
                                      USB::Endpoint::EPNumber::EP4, 128, 128, 3);
  static STM32USBDeviceOtgHS usb_otg_hs(
      &hpcd_USB_OTG_HS, 256,
      {usb_otg_hs_ep0_out_buf, usb_otg_hs_ep1_out_buf, usb_otg_hs_ep2_out_buf},
      {{usb_otg_hs_ep0_in_buf, 8},
       {usb_otg_hs_ep1_in_buf, 128},
       {usb_otg_hs_ep2_in_buf, 16},
       {usb_otg_hs_ep3_in_buf, 128},
       {usb_otg_hs_ep4_in_buf, 16}},
      USB::DeviceDescriptor::PacketSize0::SIZE_8, 0x16D0, 0x1492, 0xF407,
      {&usb_otg_hs_strings}, {{&usb_otg_hs_cdc, &usb_otg_hs_cdc2}},
      {reinterpret_cast<void*>(UID_BASE), 12});
  usb_otg_hs.Init(false);
  usb_otg_hs.Start(false);

  // Terminal on usb_otg_fs_cdc
  STDIO::read_ = usb_otg_fs_cdc.read_port_;
  STDIO::write_ = usb_otg_fs_cdc.write_port_;
  static RamFS ramfs("XRobot");
  static Terminal<32, 32, 5, 5> terminal(ramfs);
  static Thread term_thread;
  term_thread.Create(&terminal, terminal.ThreadFun, "terminal", 2048,
                     Thread::Priority::HIGH);

  // Flash and database
  static STM32Flash flash(FLASH_REGIONS, FLASH_REGION_NUMBER);
  static DatabaseRaw<1> database(flash);

  // Hardware registration
  XR_REGISTER(power_manager, LibXR::PowerManager);

  XR_REGISTER(USER_KEY, LibXR::GPIO);
  XR_REGISTER(ACCL_CS, LibXR::GPIO);
  XR_REGISTER(GYRO_CS, LibXR::GPIO);
  XR_REGISTER(HW0, LibXR::GPIO);
  XR_REGISTER(HW1, LibXR::GPIO);
  XR_REGISTER(HW2, LibXR::GPIO);
  XR_REGISTER(ACCL_INT, LibXR::GPIO);
  XR_REGISTER(GYRO_INT, LibXR::GPIO);
  XR_REGISTER(CAMERA, LibXR::GPIO);
  XR_REGISTER(IMU_INT, LibXR::GPIO);
  XR_REGISTER(CMPS_INT, LibXR::GPIO);
  XR_REGISTER(CMPS_RST, LibXR::GPIO);
  XR_REGISTER(LED_B, LibXR::GPIO);
  XR_REGISTER(LED_G, LibXR::GPIO);
  XR_REGISTER(LED_R, LibXR::GPIO);

  XR_REGISTER(adc3_adc_channel_8, LibXR::ADC);

  XR_REGISTER(pwm_tim1_ch1, LibXR::PWM);
  XR_REGISTER(pwm_tim1_ch2, LibXR::PWM);
  XR_REGISTER(pwm_tim1_ch3, LibXR::PWM);
  XR_REGISTER(pwm_tim1_ch4, LibXR::PWM);
  XR_REGISTER(pwm_tim10_ch1, LibXR::PWM);
  XR_REGISTER(pwm_tim3_ch3, LibXR::PWM);
  XR_REGISTER(pwm_tim4_ch3, LibXR::PWM);
  XR_REGISTER(pwm_tim8_ch1, LibXR::PWM);
  XR_REGISTER(pwm_tim8_ch2, LibXR::PWM);
  XR_REGISTER(pwm_tim8_ch3, LibXR::PWM);

  XR_REGISTER(spi1, LibXR::SPI);

  XR_REGISTER(usart1, LibXR::UART);
  XR_REGISTER(usart3, LibXR::UART);
  XR_REGISTER(usart6, LibXR::UART);
  XR_REGISTER(usb_otg_fs_cdc, LibXR::UART);
  XR_REGISTER(usb_otg_hs_cdc, LibXR::UART);
  XR_REGISTER(usb_otg_hs_cdc2, LibXR::UART);

  XR_REGISTER(i2c1, LibXR::I2C);
  XR_REGISTER(i2c3, LibXR::I2C);

  XR_REGISTER(can1, LibXR::CAN);
  XR_REGISTER(can2, LibXR::CAN);

  XR_REGISTER(ramfs, LibXR::RamFS);

  XR_REGISTER(terminal, LibXR::Terminal<32, 32, 5, 5>);

  XR_REGISTER(database, LibXR::Database);

  /* User Code Begin 3 */
  /* User Code End 3 */
  XROBOT_MAIN();
}
