#pragma once
// Generated by `libxr gen`; do not edit by hand.
// MCU: STM32F407IGH6

#include "main.h"

#include "stm32_flash.hpp"

constexpr LibXR::FlashRegion FLASH_REGIONS[] = {
  {0x08000000, 0x00004000, 4},
  {0x08010000, 0x00010000, 1},
  {0x08020000, 0x00020000, 7},
};

constexpr size_t FLASH_REGION_NUMBER = sizeof(FLASH_REGIONS) / sizeof(LibXR::FlashRegion);